import React, { useState, useContext } from "react"; 
import { Link, useSearchParams } from "react-router-dom";
import { TwitchAuthContext } from "../../components/TwitchAuthContext";
import SEO from "../../components/SEO"; 
import { 
  ChevronRight, 
  ChevronLeft, 
  Copy, 
  Check, 
  Music, 
  Settings, 
  Bot, 
  Key, 
  MessageSquare, 
  Star, 
  Heart,
  Grid,
  Download
} from "lucide-react";

// HIER DEN LANGEN IMPORT STRING EINFÜGEN
const IMPORT_CODE_DE = 'U0JBRR+LCAAAAAAABADtvety4lySLvx/R+x78NT8mYl3qJYEwmgi5ofBCIQBGwkJ0FTHDp0AGXFojoaJvph9R98lfZlr6YwksKvet7v3jCOospG0tA65cuXhycz/+t//6+Hh29LZG9/+/eG/8A/4c2UsHfjz22R92B9M56F32LnWg7JezbbOXw7Obv/t3/w7jcN+vt7ivcfV8mh4zmrvrsKrR2e7c9crvMx+Z74z4QXb2Vlbd7P3L8abW8uH1ZPlX1kdPC+4tnRX7vKw1MI28SJe+yu545ttJMZgkDZ28M1/0m8egkvksmvji2vWtMxyDFN65MpCqfJocCWhwldKVq1S4TjWrNYYJ+gceQxGfyBTw/g/pYx/gp/Ek87KMD0H37rfHpzElQ/LO9iOuF0v2+5uv96e4aap4e3y7npzVra7mmXdFazcfyrNofr2IIkPz+pT9+Gt8edEZ2bb9WFDVnjYy1pXOoPeyTjvYDmyXrQ1VvZ6GS7U1XVrvbIO2y3QQ9bV/dadzWAh46uTWqHYKjlmpcZVnUqpLMAMVyrCY0ngpkbp0ak6BsfztsFW4z2nrzhvcCYemWr6Su5KRPO8C0jnz/Grf43++HN8NLuD+XRNbVnjCZanMTdWM+fBW1uGN1/v9g+m461PD/v1g/T2sJ7Cej2c3P38AZbnamDW2qM77p9FMU1lsaXJmPaMzv45fZnOeNmZslObcUqCOXVKFWZqlWq1WqXEVquGLVSEMsdXrt57ctzZHJcbdnrOaggCrGD62sZAMpHs5H6/c7ncle184DsTC/VvRYsAzAeYlOFT7lV3jsbWxTf2AyY47P0f6e1qtBvkQ7t9bsd268PWcrJf4FEe8uMbyz0iX/zO/vh29QLkhUM6bZkDJwvFCDxXrppOiTWYagl2Blsy7apZMljGfKxxZb5im19ZKJbjfpdlYu9fpmCvAAN62M+dhyHlGQ//soX1M7b7B2W/deCe7XdzvX9Ybx+2OKoHy3OtxQNsgYc93Pfgc5p//ZtsI6dWtaYCVy6Va5YJjKtmlkyeY0q1MlvjGcuwq+Xa39c24u7hdzB1nrHZOXYLj5Ekn4zW9Pq0FWyenzqsBVylwgNXYadAp+xjyWbKPG/YFlurGv+Qp21j7gDNDUhv/xGPWWu9XMKLJMpSnIpgVjm7JBi1WqlStasloyrAAVDlWKH8WHa4KXdFtHSBKzUDD2obGFENFrhaqZVMkzVLLMNazJQzQKJi8w5qIIe/o4M6fQgsjQ9cv91V7wNmXv4S+360BGEqWEypPGVA/hSmwCAMmy9ZwCBqvFGdVqv219j3VX/+6FPW3xtZ70pK/1l3bJ2pA921nKuFIpcb//7jxwj6tD7tfvzoudZ2vVtP99/7zeGPH+IWXnxabxfVyo8fxwocrmWmzAo/fix31nrrueZ32/PSc/rVNpUzSADL731n/729329+h6a77uovOc1+//Gj75z2QM3YWme3Xv0O78cWkw1enXXmee801jbZJ/a4vzGX1kwtexe7pe1fT8xL+rvugvfsBi/ZbfmUed2TPac9eHwebFiL8w76uT50xn1GHzEHrTU/6yNxYYz4Fdw3t7j9Jd7GcKmV7ZZwsDhhCe94gf8Pt653Fx8bc9XMfN+AE3ZmS3u3W97RXPUOMqcd9HFnM7ns+o2VdsF+SGKft8qyZyp8D/7+wPdBWyd71NkZo95swn3MrXJvNmDrkjLi4Tveg+vwvvVMajzNuufa7G3ICF/5xNtQGOFVXnhtTevUtab3NpwxL3hNatSO0vPX2n8b+G2062djrM/tljqDscL/3rvU7jPWksyXOtA6bVmTp4r2NHtTnlyzJbxPRh9rs9xnpPfdLOin1e5s7KXI6Er93eT4i92oX2z4jqx/U1C0xpMgNaRz/129vDakcI7i41Th/eYS1n4pl2EtmG6jvoR37axzfauPvIPUFM96WdvrI56RWrZncRrjrAYzm/PO+tP1eAy8TxT2k/F8CH1aWax8VLn50T5DX557j9ITrmfQfw3GBmNvdY4md5rJ47k3KWswntkmuMc5BfNOPsfu+emj69Y7aqNe19sdzyr3Pak1PwJdHaTGvGyM1Nlk6V2MlnZ+GcSfTc9r/VltzpAGGZn7OE6W4k5biue3YB0ulbXkeepQE+Bd0kZ6rv1JanR2Jtefm/A+qzxwXxN9i+beWoplZfz5d6Ta2+ju01oaB3TBdyyGZ83Wx5u10PZWW+Zf2p25zXinF2XRb7jhHKXnjHy0pqjIjKaOGW8A9Bv08aAutZPZEt9hzt1xQ3K7jSdXchcHDccC65DqE+6RxLuQhnpuZTYYd1b2iPVMoA1991qz3Hp/Mp7NVOAJOuxXoyXs9FHl6lkN6Ahon51wc89064fJqL+WWhrMo7ZP0h4/N0fawTrDfhiJFb9dN6AT8ml5S6ABMufQfx7nHfv10uhE9HiWdlJLYGGvbLCvwMs8a8HOHbF/NJf25Z65HHPR/VpLGMLYyjin6bbumTvgiQvYv8DTvAPMwdnkKrPJWLvgHBpA3+YsScOTcX/b9Tqs6c7pM+en9YvyJLy59bnNiRsY1wDpxRZFVh9r3mDc581lD+6BNSXXr9b0rI9l1lpWZkC/rD7c+X2M97d+gja5yViGvSZenBH/Lol4XuxmKtLJSpbtkcbqKr320gjmsP6YWJ+2fHaSezJ5nX7nnxtPa+BtZ6nVBx6vHWzkZS046851ctYNuI8N0gW8a5PRRka79EPaRL6B/Kgllicjj4newbdhLup0XmcLaTln7PZTtXsWHuP7ZzrcPBL+2maOk3F90y1PPrplOt+wd3LfbYwms5cG0PS4d1DG/aE96r/r4/4FebDd1i6UFpL0d8+YyKfZHygNfghzshiOtIvFiSvc05UN15Oae6BHHs8Juk5K/WDAPgNamU9WsOZL7dB10/zn6v0BneT2YzqIeHvmvLdgX6xkwiOANwb0SuYDxn4AeQXXQEGZZIDzQ/ipHaxHfv/a+hz4DewdgcF9qCwE11iCnNHgB5Nx56IrczwfGUIvIX1fjQ/oW5oZQOPmuIf9I+2NznDGghxlnTs20r7U3NStVWfuYDuznP5QPuQ/B3sT5tuGM1Vqf9TgGvSDvXQX/aONfA1kCen5KYOG8/lPrM+E16koRzVZPAvnOqeupYW8ia31Bs6qGZyPnuVW3Pzx04+11Bh73DnkzzWTP26UjZp9FuaHrDHIZwsdzgAdzy9Y2/x9gfw9eE7ugDziOUR2YT5y+9HSjxacj/TZBcpJp9dzHc7pU7CGSFMs9OMRrm9fzl/cVz5t6WQswDdc6FfT9mwR+gr9hPk6v/hrOuI8+9b8Eh7Qjp6VGk3ka3Cun2Ydd4Lzj3MFe6JjSqu+R+VlbSF5zEwaMjNzpe3MxtOyA2OfLIWj2fCivnk7F+QzOGdR3h64Y4XQHmOtNC8pC31yDug970AX+C4mWFdo+wbPoB/gMd5ktLsxz0ze+lydm7FrREYCmfGM82Y3CZ1VyJ4C2qH77ZqusN90b/LPZpmcLXvpuflr9+CxMX3fqiDT9lDG9wyUT1t7D/UVqW17SKPYZ8mXFYAvwHX4zq2PgWcxcC68G60PkM1t7/fmzSiHDHevC5A/LijDBzIbnCF7kLl2Zt5+b34gb6nB+M6ou4EMAvrcnAmeR76nj0FPbIEu+vwRyMe/wZldcEYSXhDwxlnvuYjPpnnANY2+gL7wu/AFwuvmHVmTqC7UqP8F1qAK59kCdRA874yRCPqNOtNiv+tAJzbe91S4npSuaT9nb+9Mpsz5otRdoKG5cSmYI9oeOdsi3iLhXKGso0R8zT+v2P1mrOSvD513cr7FeeI8OON+AZ8J9SjQixmcM7+vKtJWnHeiruLfc/Ncozwm1LHn1kom52JR26B3H3Smw4OOetA1YkdxQdb+09s5/xkLdF1ou+GMPlCHIfcUyYSxz+3+g/zrtGVfj+Hremuw7jSkd4fz90tjN+uNmarU3vvjk5EPzpyyDGv74U2VW3zE59eU7rYvl+I5neatdZGMQGknzieC/Th7c59OufTTviG3+DxIarEXHWX7Rve0qlRZqfn4vGn118iDA1776oKOC3MVPNNdbI7GCHRxt16TGqgfxuf5rr2wtzjrMAQer5fltfRcmfWfF6CX1/F7pDFyXS1rbvDOl+ennfQ8qPTPC+RRbtetHKT34jF+Xv4n/SqQm3PPXM9s971/yPMwa0yp75J0W38HvfbdaDyt5fEc9LE6Y4wEeLdWebmtq5KxDlvCSoZzxyxLsB87yBsC2VsE2eNova9nDqdVuotgPjThiieEfczRu5sb1eT2aCNJ8+0XOA+2+qhCzzclT/fueKBjnuF5wudBr0G7D/K2iy3WYV61nbb0FvpIiLUNOg/avXLOKvI+DWROWBfkd7CugwmspynqGzhnjlq5M7fadZBLY/Kux/wJ3w3j2sO68mp0JrnjoQAyb303GXs7Y9xn1JZ40EcfI2ME72ETbYRji8s1MXtoeIagDUiDtbQb0TzFzsFd7EzY6uNFjt0xspHE5XOD03ja5w7wrx7pf08k42MI34exdj35qAZ7vgEyyqWW00Z/Y47ru+CcGQ9rBzzn/XGsXxJ2mY1wDaHYOtZ6uXE9J8/LbjuecVbQ25/rhzeOjuzsDt5+uNZ8p13RvYm7slxP1DFnGuVHm2G4ElupmOgEFUpCpWyVjKnA2IJpsI+VL+EqBPz5A5AVv9hzb3JGxbFrdolxpkypwjzapVrVYEpW1XCmlmOzVqX2D+m5B9Jx9g//0lw625kDJ2epQV3h//qP78evTqtleyo4JZszrVKlYpglg2fYkiAYdlmwOM4qX2O4fLc0x9aqJlD/o1lG+FfZQMiGU+Iqj0xNeBS4sjD9x/Tjb3G9FWdHIKR5vvysXt7lzrfMqlUT2GmJNaqVUsWCKTONqlWaGkaNK095pyb8jzv/79+d/+tbbKy3zh+PO8gBCPxyd36++3y41Jjugrgkctz5IOY8Z7rSVXQlTUYyvgvuEy9GuRdv41Uf2wy6kE1Oh3ds4P/Kresg9noHa5j5vmeT+yBmSBSlQVVtg0gJopv3XgBRQFfkyh59zK2FVrGoa3eD78x5Zo2mDx1V82z4QGfom0UiN3MfRMv+hahKTe9A1HoQHyNR7xe49olZaP82XOgdmdWUgSZ3hkzo9kT39dfaHzLXKgGIrvD/ZnKOxN20m1d6b57758qp+/506CkRBOCr0IGi5wZavTNmdVH1+jhmAl2w35uRmzwT9kDoElS+D15qIm3Xn2FdiPvAaMuM1bzp/nuMmYdxfvddhZkNFuLrcKE1JZgPrekNNbE3g+/3GeMgEBgYy84J1QbbHCt1F1QZUD/kum9KucB8ZqtWjU7daqHaNHC7ISSCSfcrvpYzla2/Qb9aI6U+GmidYYLu7oOJDOGdsL90PpgLZTQgcx6ZEYppRS3Xj9Dm0lH9ORb73qQMaiJd+xvrdt0PX73KohXYsyKD8B0Z/gcVZ2OO1Oj9mnwENegA6vfJAJUQ6TZ232E48g7aUtzZIzU1p3WYc9tzGvWmPtJhTB7hNxHMIHP88fUOno/G0O7MJ9xes5Yf/rWQ7vy/50/SUjjBfFvdVf9kluWNvvKs7rJ/NJXa+u2yQXf4rqvt611tM++O1/uxsju+DAWYL/HdONfWI6a5Hy2be+f9af+qMdsXBdRQsePpnFYZlusBz+zoHH8EHvcMPAv6f5ohfwS18s1qy4QvogsRVMaN2dIWMfXw82Medza07Vlosvf/Xg8aHccK1mm4oWO4rDPGALTf8NtuCqcA4qWM7IMJNDXgxAvQQS1jnHBWsCdj9OHp13v5U5Atqam9amJH/xQULNpr7GT5gXPlmpywg7YqcH6xQPPr0AyUMkGGJkcfhoN0i7C07sL27Ka9M7nO3BT1ufUed310dK3JIgTpymTtwwOCexEi8Iom9WG5I8I6M44yP0/GdsdqLDaSKNfVhS1qIkKHgEb9PnQ9ODdbH0DD6lryTq7knmaSK23gvIS+MtSMkDTNhjxzqIqvmqr1hk1NgXUSVThHpMb81R5LAaTnFeh9earKO7OlbqQGs+8mTWTUbTHuoHlatVYemqpGk9EHi1AEoOUL/D1EyAMxsUHfzLLGhC5WoHO7KbiGuwhcoXj/22S5TppCFF60xtrcbPdgjPIZ+ALSXgAXIPQEfdhQOKJwRhkB+pDYT/fAfMhaev3kWrozd6TJ/TGDMERZ0cei71aEPdxgPqAf1N2a5Y4ITLRjuW22BDhfPkaTsRRAwHwIjb6xVn3k5T4U60RhOZkumdDUmoCXBTQ2BDnPbu5h/9mHQdpFCu12h80dQnJg/javZ5+f4ho06nObwLDmG30s5Y8jBTWpdX5T5406vBvONw6/Bx7g1re4HsCjGGi3ao+7z8dWfws84ELdZc1s101kriTzeQtK5e+dubW0L0jrjooueh1oBNai0SH7xlzVWbsRwr8o3GPEn2xKY5sXJTLz6TCXFpc4b6L3tBCW1gshZv7ZtJai82BqkPUDvjke+JCjfgf4G6VrxlvE3P6wl8PnfNlHhntxT+MzvGqywVl7Bd0q3m/h+SpcgJfB2K76BGvYg308Wfq/xyAGi2L5gN5/baJMwtUoL215FwITK4M80CZuWoSYXvQs/pc3t8tEG6lxgHwyEsga0rGEfyfGQ+ESZJ4CWBCelcch1/lLykwbQgQtlrQF8o/MZ4wvclUi9M8lkLKz79I6gMwDskC/q48XQBtI7xJxH9J7+mbw3VhJrrH0DP326LV8iKlWhjEsqMxXp3S/IPCqOYzhonAaj3QPehtCe4GOCIR1RmiF3bmx5zPfT+bsOfe88/QWgaCiHEJpNXfc6Xuv+rHQRyyVFxYewlxSvP6p6u+TJP97Su4D1BcQFioDz0CZB2GUIAt/9J4/Q2Ohi71pjztz2icW2tYYfdxL0lwL+MQiOqsQgkD4joauZThfguvvKTO+4p95cCYBfZ0IHY5keJ+0ucPdhDDWqG9Ib236Pr0J70u5D68gHxSyeVBX2uElgHE2cL2Z35Kuogx+HEAlRYTF9VE3J+5RkBM/4NyCc8aHfqJNoK0xmXuqTWg6zQ92hNdzsCZNb9FFVwu6e3w3HNAn3A/rguNbiuS79HkxzYW2Jl3qAbTNP/MyXUifkhlR12/U+wPVe5Waem/IWl+SXWN6kg/ppTDfm3Md6WCx8+0U26fBfFN4vTHuIzQYZCAPZMlTYj/H5j/OYxJ7s5u9z/JcZnBu35axcL5RL/9VnwyXNco1wwEzVxRNVqXnZhXOWw3+FrPvffplfYFPhlwTrhlH3JooC6C+O54T3cr2XadA92sC0SfyySDT3R1BHnSEfyy0CC5DoDj3PDMYdxh0tWIfQp6fAd2gsMWiUISw3/QMbrIbnZszg6UW6pl+uALhD2n5O5fvxOScwlCITBkqCxqeT4ux9xHZEMZ78ucU3cSnYK4Qbh/xQ9C3QMaxY+OENVuaTLBHY2O+BxparP9dLJFCeTLn7+7x0Y++FFjQXVSQbXa6QmS6YLz3wLSWCJ3Um+LZRggBlQnDOboHZkTPUbTzJuDgIFeK5wk3b4AuwgxHIgO/UwhAOKc563IPBIzAdWbzCPrjXYZI903hrHEEAgfriOEwcxff311FdA36QWLPTkA/tRt8+N0NiKaQN6dZMKpsuOY9IUGpfVi0Z5N8Y5MFvcqlI6qzA53qRzIXIGcaIBuB3gfyZn8tL70zzHFq3aK+5cO689dHxrOovUC459I88wyl28UG+MY1LaNtf1k7+PDAxyx+57cTQAEfc6FDP8kPvzCvF1+X8HkM6F3jzrvRpLYBH6bjh0XMY2d/PlTNps8EeuU5Rte5z2TwB3iO8p8iWH56nq2ydJgU8IUiWr9jn4b775NnSiZMrdPouqvJiUKgz2GYzEof6TgXnomhbu09a3HauRBOGaxdsz83l33PFFN60EKr4HxYsH6Rjna6krkKwlUKIN95kHmUV3+drNXNoGsSUsr0JXXhqVrj6fzq1utyc/A36QvV9+tzvSWHoVZxXjUYycD7hGToWrRvd1Kj0xl6fVH15OlA1VVZ60wHrKaoC7QzCyNFlcXhmdJALq8eiQtdxPBGlON7nwpVC/pJ/LVnvqmPPuaOMmN7z09FdBd/X/xcrcM8gJ6fDAuM+MJpJi28V5XRFBhbXfZkGLfwrGkdRVZ5dczqHbmpvd0R3paY76/CeQPbK+y5PrYzGdneS2NAw9lE3bOWKCPJLOopzkqdoU0WeI9ntD5WAVQUofZdt/7klFEP6lxDLv/wPUs/d4VY3XkOkf0G7YGuNRu2hKPVeFqDLny2Cby2s7FA90HdkcBp/ZBQGCerr2Ri47UbGTxThDNTo/eS0ET0+8HvsE+G6Mej5yvxiel2i6X7RyO+Ji87tIPqjf55chXelXE/yJYgf1MbycYPA5kZylNNep4EYRtk7P3VbGYH423M3yfK06X7PpkBf94Su0HW+PLPhGCv0DDbBfD7lsi/PE9OvYKz9XpuAjpCG3R8HjW0A3mTERsLa4ydX/m83pe1w/Cm1Dv5Vvx6sWw1T7aFdmhYh0Qoyd0yUE7YXjtBO1e+h6z+5ejtsPdl4CcwxhG1yZst9M9m2aduy42ZcxbpUxnyTnIccvx61lp9tQ+hDgWybJb8VPTMc9Z6hTYGf60j2xmFQueOLbItvmfbAf54e02vKol15cR/tDSVb4NOMxs2hbaiZu2VXy9T5PSvMVD5V1kFGYKZiwMmjxay9xq1j3iXwVI8mHB2vKTWvBvs9yJd/zYPU+BMOtpLTSU+e0b0Q+LmAd9J9K2A9+TJyacV//JEwzWsY0ivhI7RfziZIcRdanZ2k1F/S8IMGpWZ2tYOBobiwDWCJWnL6G+864wO5TZOPEw4bacmz92lPJ4TnM5LsT25IHTE9znGUqzE5iFfpm7KmroQVUUVXkF2kGS1382TB1Nn4PxNedr3FAznrXcwVYrJfOB8BvdF+5Fi5K5t4X+ftBHXoUiYHcpoJoZznJ/Ww5FYkdr7pC9jxcwQ5/Oi/MPQyOdkNEZAHBrI1NqrnNE2PUsRwyTuovBqoI2cNAPUj5Xwo3xKt8CQfMRExGSxs48BiPkI6gQviWcvhrjStCw6nL+zMIQrZ5+kv8sJJ8vvHx0f5YvBfKAvtzv8cpg29V2Mvd4EQ4uW2kcsjD07TQ/Kn89hip70c24h1iP2iWzuBDPSMsadC8hCi8/ghVQqA0TPFuJCYp/CMOMY9mehaaCrG5rWfV41+12VrSsKnLddVVMURnsdIt3SewvHGqb0CVIytTFlT32BNOTP205q20f4bCy37uojby81P0RN3KiyimmEtCXM6RKuz1Fm7BaHNdM1LcK55M8xPvvbvViZXzTXmLrqGfYNYugwfRqGCA7CMLzn2uylGeJ/ZhMahpevQ9M5CDEWmI7NT6NCZbwbsiidt/B91F5cPIaiz6fkXkLHYspW/eV3Ez7F+DZntHFiOPpHXC/tLhK2004Ka5hLyyS1FTf3QOdAvyHsSZr6TGpvWGv3Wptwe7Q3nIBmD2hveCv2eyB/HesjPghtncM5x+qjD9A36j4vrgOL0zqwH5VAljLbPfQ1bEzgxwQzhfuqyc7NBtAl0KoO+rmz0s6nx493g8MUbfuN1a4zxXuH0ON6uBTO5kiEdjtl2IuI0SzD2izw7JVaNrRpPq84/F1YYNqAyfLDM0YdTAW3g/vfjcYiN60L+QS+55W2t1raYkAwsEib8+t0Iv46Khx/tDn+OX0dcRaFez3QZYtS80Rjv8T3YvAOlWAOgafsXjmQGVbF60llOpB7MT7imaQYwrBPknZkw4I84elNoq/Opu1T9tnzfqXfqSam5GvSlDI/n06B0pwBawdyC/Dj/rHr05Ree11MlupMH/dmBodnuzqj5wymrxDOlHcDjUFfpdb786bFr4ge3sKUM3uSkg1lgXAdsN3ieSefnDM4TQ+308XcXGPEq3b2IOd4oIdg6PC7gViipVW476kshvLj/EjT/bAgo84OKLe+XNk7Mtf1VroWmnoOcUggc8TmAO2Oa2L7wrQlxbzkjjRDmNYRz73gLKxc6f1aS2BQDqTpcBZZfUryUU8+wj07haZSSaRzzP6gfsS+aQu1sL++rX5vlnWP4skQu9nP9zPF9t9Vn92kvewX7KGZORI4fZTwU/exr0THYbyDL59l6k8oJyLeDXi3TzM35IjctAz0oyN2UskZO8jISR3z53ECsbFTLC7VE4Bfaegbu+A+MV3ESfbXyDN/bt/Wl7D/kP+F8lv4/nN6HhEbmNAR7jrTNa3eHGiyqMIYVDhr0YajLip3+SPuxoIndbkIZ30HPRf799N2u7ifPccHmv58God+S5a6LR/fj3G40knqMRlpYJb7G4p9rC9B3kEc5hz0i8OpKr8b7T5i6PqTEWLb6h7So454v6s4hRiPvLZf+zaZL/mSv4TDT6cvK9QrC2wMf6xddlCVmrooq3JjkGnv+kOxdAuQwUg6kxgGLmFDJWlMYlisYmwc4kFIGpJ6LE3U8sru/hVcyHXbVPeJvvf9DzyRJycj6O955mIaJ8n9SqpTkuqK+L1BbruQVC0anRPgZzBnHvOCvjx2bztnCWjoyZ0qJ9B7TrMAu6tCv6BPsbgz/giy4g0MzxyxzYx15nsg061AfiJnU89dzJzYeiX8HHCW2e0+plCJ0g9nry1tm919IHYdU8mg3/Ge1D+0f5nrW4S7u+ovwfE3JBex8p1G5zGcW9WnjzZD5jLHvxlhbFvCZTjur7LmMsvGB+t5tJggxZW0HoAsEE9xhTJc5S/cAH0miirgXtUz00q1NIxvCexsSbujb2dLv0tpeQfQM0EHMJ+PLRvmQHrM0tmpfJIhnxb4/InMjanUGtm6YWD7w9iBdH+717oDiWFIY/8Te92fd5oKW9tJzydBem6CjPHkvjRFTH/+Gp4p495GckHWaAxcqbyH93wIsfRUQ5B/dhOgcT0WXx1b62y/QXYM1UI6vFjzKHXrY9DP6RBTSKXpVhZi31G+MWZu4pMy+hjItC2ge5C/Pn6R3TxlC271QWbpr2F9RafV9yg/AX1yPEvytSw6ofPVMzkb04EdEAsyYkmsBspdLGI1x59Jt5U8tzP9F0BLDMoPaPeQl9rabGnnvNRjv4/fIZq/T8co3BEvi/H66E9VNU3UVHWmNLUeyMOK+ovyIdyKb3hrzKP4qZgsGcUl+OdUjF9OQqxvJcSaDhCHS3T0/jqFjUynktxlpIC8mfLrLmwr0GOUZrH+GPQzsQfjslsspn5CsVgU53U5raPxx7BoUb993GtsnlohfuC3G1jR6NwBHcJa5aY7o+lCiV1amOtRDPwjtR90eD+/QWzP3pXaPUhDmsDhqcDj7CbmFOG/kHp9X1eb3lRbAN0y3ttwxRwtf51Qto7GkI1LovoWpoMHWY0NcHN9Youzx32QwWQvHhf6QmPRdlLy/zwMIBnvJExtHsMGkRT0VMbTSewYyYNRt4I4vJCuMvvtz6NwJG02N2+T5cablAcHFWgBzvV19M7855OY4M7RxOf99NE0lwN/eWlIi64bYdyxNIRP/yDTyp6+FFmzPVi/5Kari30yZIWI1gdhynWC+8O01yLNC4Hyb6dRCbDcB7S1g+x3AtmP8dOr3tcnTN16095xZx84bw/ynkfxNNIm0IlBZsRcFHM4RzE3SVb6v5v6OV1XlA0+YE1lmvZx1QN6HhwC/DWsyefGnqlLRryQykEF710iLsFOpLXtkrSHVF63/+h5WAY8r3IAWXAPste97862EYXx5k8JTCzG003Sdo2UTjHhMEZlhnrNbT5xzj7Tc89I6j/5TWoirhfGkbQz3jg/QX7naE6UvBwWgY4I63qcUBsfyf/hxOLTaNwf8MWVHLO/kNjTsP3M80D5G54B1I+BtqsTphM1OTEbXxnlGSguy3EVcxqkjcUzMWwjiGuP7F13nfkfxIf75hbalCmGFuRbUw3tRL4fQUjZetOpX0lMSTgPxKa61MoYNxM9i+spHwOdapoaL9AZnymX07b/grk2SOmNFcjkJA5dB3oh5wmmPt8Z442HMcF4trxE9JYpS9O4MF/vjOV8iuJfI1mdjIPmjUKs6NrkBmvJq9e1Zl8C3rhDnY3kkXpeH4FOYiWg6sLraj8Ysh11qghzq7U4Oow4UDRhJGudIWK54Htq91SEx/i8o0z3GTvMIHH+k/HEcpX4ZUlaJKca5p0B/UHwS7Jpqvw+wzgETKO7M0Z9P+5boPPtZtkomaw9F+NLQcmbRK4tXwcKYrhx7hcb9OOrZe19grk8WGL7ZS2mf9TT8YFtJpMHBjk0bqY2TpYUqhFf0HMFfbHEH+TnZKoH9tEgdoH66VI+njR/K6ZbzDlzQptWAredmhu5paHfPYyZ6DQ6a1Juz60dHTaWh6fNVB22/qZ6stDlxJMBdJPMicYLQZkgoMUN2Xdt5lb+k1gf82XUtN4Y6tqwx8O498CnlnMG/Sq9MtAnVeDZGE/yK9u/yuV3HauQwwPD/E6EZ17Z4TGGkNMYmBv0/yPNRvi7eA6B8P0kNiGBu/9iGwl/f04bp9T6huUQw7O+mfbJwLnUsj37eYexENieQPIBummbXWZbiXhy2NMr2pc+aS+VPj33+dC2ez2m7PmI5NFWGrd+dxt+SRLkDXCe+u1gPI+8IXEE4971eKJ4lh72N8D9JVNu3+Zbo7G8V+NYjmGFpB9PfKfhGLW5OYrpeDHd3vdvRv68QrkNY6e1XexcuR2P8xN6ejIf41dLpRXKan5uR4HoVtR25ueSc3kl5IPqHHVlkC/6pFRYJv8MYjFgDAXn2CbFZ1F3ytEP/PyijTmdG6B1ePc+Pj/0XWGJM8xnOsczVfXvjZXiu6N9KcrF5z9P2sOylm2fhpRMf1CyfB7Nr+nnJiI0Qsq0Er1VDK7NL9ZnfUscyKPAG17C9mnZtuxyfPRzC59L4n39MaLOhnq31vZOOi1j5feb5Jg8qO3O0YL77Lb3OhmxHvGhRfbETdQOzQFGS0IFpdyy5Lf4WtxTSuZq3PfkTPjcGOFcAJ2Llpu7x69/T7/9fpD8qhHO/HRPvgb6DnuNuRpp+R8RMYGUzjGPEMk3EM4L1dc9mbeATtB/Q3QDf8zdBfWlAn/ni/E5Xxkf/QSl1rL685buj4d8ocOEOsq9fbqxTwqeicoNKsSG55f3oPQko76hhHN8V9meqz3q7/+wbAbmPLhRsiNRjoOUOrqjLNE9H1oir6C8h32G8+GkjzuJ8iNvmCMM9/RIPDvadRmRe0uYfH59sveNXzplj/moJyyev3Xg9/2NvdSI7EBwcdpVqZLPz+GXS2xlf+7BeWXvuXi+ImqjjZcbjOxOsFbnolyFnx77JirX93SiNnhyPl9hnkjp3eWt/CufmOvrMorh3PvnDLHXvIyjdQaauPh2Sg/ngpw3PuYrktOuMc1YipCMs8BXfePzxefuwZr5+NE0Th/9UrSMYr68+mk6+/L4yQdlL7T3dhe+7sEBb2l5C5SBg1Jpxl3Y3JvzFqPDdLxwgh58P53Pw9BncSa/n2i5n5wyP7S8XHKP+SXuPlcm6BfNYxyfEy9NmuEP8Hky0Dx/Ib9f6mTs1DdwzR98TFZiDxkt4Ww3kyX3Plli6QtncZwOw716rYNezwH03WYM8Y/tZ27Zvdt8jtrKzjdKsWbTfW7+qux5LMYwf6XdkDaTGPTP8dB7+tVCHi1u/6h8Xjd4V1Ci9rfsMtE38H8tnUX9VlcpPkL3S1uneNgzxpoBD8ccFZeuZyNu1nvBkqrDCubd+K3gDMPc4kdS4vU6/2ac9kg8vE1sw1qf+E7wXQvx4Cizzct1nyK/xPUYSE2Aoj3kY+Tz27za5wkb0YFgdnPGk7OW8RJxZD3vwkLF7bNBn55z/Ee/qj6Jn0+hq+racLEnceuy+otqlGT5umhsB8gXHZhjHuSj+RWep3td9jUPm5KbFyyINZxEGE2Mqy/CdcZyyF358BJ8Ql8KyBNImUg/b6E/FuA97nWtkDty+d6b38xvm+QfJGXs4X62IP9IOP50afFwrhf0HBhyk/XEz0Hx+fz5T7/5cnltmhu3GcxvSn4OcF2/tB+fwuuHe5XELeTh7FO5lLOej+WJv+INMZ++X1PCw9LNwCsxL0K0B/Qwly5PcRWxPLvI52xyDuT4dilfLcQup3JI5OW5T7epGiPWU8ugV7uxnOmqVpmgfaSVzilzIj7lEcugff1JWrLW66p/QQzWoNHZm9qpapVJDm24Nrdel+x+/Ly5WGcJ5uXJNVqJ72aIQad52/182SLWgiF74iC18vNfZOm5kf8rei6QIaL5hTOO5NYI830XYj6ufGqfwfid78HZRrmdE7nGcnOwF9HHjZxEUS54qt/dqEGSxqzeWyZXa9sbPPOSY9aBP+kb4FHxfuwyxve5crlJ38wduNz/LvPt57ZrfC6H3e8rj/QHQ1buyB7m0q9LsvoxQAzGr/Ub34FBLsAIv7mkNsrRbOteVBcDc8xeY2sNP2d3jvxCcvVl8qkI93zGnEl+bYfcXN4+TkazlqSmRlY9pwPNnzxbGwV5xGkMCGnnEPrJMBaY4i78+g70ulzuHO1x/TK6iHbgWynu2ynZt6v6WjzVBdDel5vDlspKpgbyWYOPcktiPCrJX0RtgP71tgWyvoVxRBoTrxuW2WZ8jKF9NR/vW4jztf3y0rEYYfSRRnXa/H772NrAd5q/Jm3qmyC2xKBWTAynGJ6PtL5JkR/3I8R8UaxUGDMRKxVPfK/wN2O0hAXJlwJtB1gX67I+UkwLfwnGQ2ueCVxP8WublXtHpxzQrpwXcwFz2zwoLeoDQ9ucjbitcmfjxOwspK9RLcdXfTw4KOh/bvAS9Yl0UHdk7dYcYzc3iD8i/NFvN6zpseggHt6zXCz1TeczG28T4YEKfN4kXifw4+K83vI9Q3+/gisvwMURnBjS2Evgq+p6Qc2RGLa8/HSIcGfUpzRAbCOVrUPaK8YePa0N4iPbuRRje23DA3mOYNFG5848rJMYs/3lPXddwyMLT3lN45/FkgU8Ffj3XXuxSOdM1ytM61fxmoUajGW4FMrS8ym3zmF8/dP3vN55ZoQ4EOU2VpLsH/gb9sxRb/CI5WWwxhih8XYPsRvAC/tog8K4zfQ+JxhJn8flYtYsJYppiHiODvoangUfIsgeRx3zwIS0OScYB7nlvRPZA8bjDMP8V9FZfKmgXmFKSxv4C8+My8SPi74Z9Ou/+zUfplifSsd2Wx7mOHGBXm7UzkAeQnOAQb854CvEvjhYihd9OGFCe+01LpPkCxusPNQVEBP4eFUvq+ktCP4lr44WYv+y67r90TwS9or3TmLRx8D/i88S4Gn5WMkEjpTQw424G+BTuZhrZRHTszJqQMX6RfiUmxMLE8PnwNzcE3OTSTNX+x/96T5/nPj9B7qk19J1rLL2S1SzhPr+se5xyzs7BA9AbLFEBwd6YyYMf7SJH0uGMwjjHkFnIWcBD3uCPgfvnxqwN8cKT2vADYMcZwuMReaycxjfzYNyMKV0XW7y5UimFh0q38awinfLzvfazAJZMm7Xy5Cj6/59tF4E5gVI1MmMrZcfi03vidVZe2l0eLRP2Arv6koN93NsboI203H2yWemykdwLkP/PzZ2rH4qnCEHXfGILEvj8AfrzqW2etHQj3h3H7k3RUK7z6Mv53B+/Quc67Bdar9hH6XVRJBWzO5W/D/qAK8+nnYCuiPxw7s8tbE3heVLw1p2zot4fMTcHD/N3tynE8Zxw72w7zvB2q97GGsD7ZCab+3JNcYzmNdQV0jlFhg2yTksjbLmQML8CQXXqZyLORawb/7czF7TdBPReUzmoDnOhiNvBWdpQ9eCfb2IxXL2SJ01+D9WI68Xqxm5iJ2p+fIM4e9iiDvxQvkd42HTMTSXD/XNjem3484O5DUVc6bYrWZh7GeMn2J7sbOxj3Xc50DPVV0VXGOpvcMZjr6qeXrPRPsg56wg/Q3OCtTdTsGZ5vPjEEtJ5VA4n2S4F2RnWsdek1uvWLdgKZ5w3wTnW5cjMnLibEX7xXTwH//x7d/+9/96iP1822wda73cuJ7z7d8fpoa3c9J32I5nnJW9sd3n3bEzjo7s7A7efrjWjK1rmPmt4b2Ju1YHz0vf5Npw4RtrPpoVhnsscaxdLlVsq1YymEq1xHBl22bsqSE49tV4To47m2NPme9M+tr+vME3CvhzNQ/G1lntJTunR84Ku4tX99vD1aDcle18wDU2/v1foz/+HHvgm7X2PGOzc+zWdn3Y7OCx//xzcPmv4Y3/FXuCTocJJw1nCUaJsx5hOqomUxI4iy8xU94x2EdeMEwuPh3f/nJwDjjeb4z/U8r4J/hJPJk72m/Oh+UdbEfcrpdtd7dfb88ZCx2/681Z2e5qlnXXyliS7inr1exBWk3XiT7McHbw8mTYe8Bbtg4MaLdP3GR4J+O8kw+rrPa3xspeL5+svbvOvG6tV9Zhi8uedXW/dWczZ0vWJ76s/5Vae9g9S3gRoZxvU4axhPIjU3IcWKgK5zClWrVqlyynbJrcIyyX/XhFsnR5q9XHKW9UmBI3ZdhShak9lky2Wi6x1cey5dQey9OpdfWoT9EVhv0cwZIF2sG8JMkPf/LIdncw6VTenJFgXf+///vPZOEe3NTakrtsZ2dt3Y2/ON+urm+dqQNrYzlX7yOXG//+48cI9t36tPvxo+da2/VuPd1/7zeHP36IW+jBab1dVCs/fhwr35nvZabMCj9+LHfWeuu55nfb89Iv/Gqbynm3d5a/Q4t9Z/+9vd9vcpr+/uNH3zntYT2wxc5uvSI3Ju/7c3pWzfPeaaxtsj6I4cRzUS17F8R14hmf/g5kHQ/kDKJTZ173ZB/PTTB0xKZsYQ2NlY/nb8LzoBPAWX3U4cwjmGOX78E1v/bJJoyfmXCYR65Hcs0pIx6+4z24/vgr7eDYhsIIr/LCa2tap641vbfhr7TnP8Xaas47sibN5KYnSk1vADoN5tzra1q/o5zZwQDGKqveqyZ26jKjvYJcV+0uJNCrmnzPrXz0QcfuDa1K931wjuJgIp8ayQ2fjBuKxXc+Ia7dNVvCO+hCa7R1SLG8/ol4NcScNdC+IyMGZG4tBzOKeZO4/rBXyXo35lfAvFGhfCdi3N+AvLP3PmF7l1ki99NPrl2mPoU+4wnBCooLkM92jhLEz3xsiP0lKW+F8SRKwqY5S9i0o9g0KtPK4zno0hqjK7m2sdSc5+RSj+w4QZ7BjkprQf9JanR2JtcHmXJ+hDktqHktlpXx59+RVTO9GPdK8sRdYQqy7G/xWCeKDyR9xJgIxKa/Yx32cUNy0c6GuRrCvGaF2CCSm+vT70ZMJsjAOwPl6oZU6L9GesT5ozWCOweMoaH5iLAuhDqzW3OsHTXHfNcmwURJM6Axj9i2W/zRbgAtjdBnmKztlqo9HNYmH507JCfVLbtIos8/U6/6Ks4tfx5j/GqDfQ5yaid4B8EO9NeYO05X6iPEpUyAb8PvCfpHmxvJ0Z2HiYn7Flue7x97+kT83OSjWyY1V/a0fmVWzrGMuYx9cnVI5c54aLR7+j4Q7JMGemUB7jjve8wnSfNvn2m9L3NZi+fKWffen/LjcALMfhQbnfCtEJ9Zlm1UTMT/oX0lisH/pbXqOl0dYzwVWn+tS3zFtZm9BNravdZ0rjO33Bw7euxzV624vHy67WiNMd7KQrrWcnxRRfXNQlt56HsK/Jvx+f9iLiOfJheBLaGO9oYVqaF8zrbnUltAflt53xOeF9TZbgR5tCiPCzFzLf1scgzyPw/ePRwyeXmBr/CKJIdk2Hc2jtvPwvg/udqI35pLoWy6dT+GIH8vX+f6IvVYEYPfwRq8kf8tL6Yg8b4g76WbS1e5mD6C1/DIuRDxDcYE2cvmPJIDYsLN57n8Ly/v4SrIWVivSe194EvEfP6zKK9adhxcFt46yEfx0tQqE07zY4jr2fmwb+T1HbaElTzunIFHoZ+H5hh060udYJgJL78ENRZhj1eh/wTXEPCCwjqx5Nzx7b0gx7y69dfJqA86hfdutNGuSupPzNEXr8MZCGfyCM4YF2NZbFrH/armJakbUbR+2WvgKsB70d7m1/Ta0z0Y1sDlcF8Mx6jX7PZqE/SVEcZ66FgTN8cfmMJQKiD/EL5xhXnIthvS+Kl/ABvetfZObRp2xRZq00q1VCkb01LFhH8EvlYr1VhWqJl2lXl0+L8vCx7ze1rwnArPTHmuVqpWpzAnVXZaMjnDLFWmU7NqPhqPjMD+41rw5Az73D+mEc+yrcfalC9Ny4JQqjh2pSQwFbPEVB2e543aIyxfDsELzNThpixXYkyeAYIvGyWzYrMlg2UfWc5mH3mn9iUjXuY+LLLi/VvRcLfOydj6o60yxtSyjFrJrlYqpYrl2KWaw9dK5anDPnKOaU65ayu7b6CfVgyzKnCwqafwKGsZpdrjY7nE1SrlWg3mrVoW8kbLstzfoclScfYPyma9d6fnxtaxgapcA2TpB6CNB8WxtnB5v35YGgvnwd0/oPHu4eTu58EzD113tdhdDRn4xXqLzf+zKKZ3Kl0PQuS57DZ3GBlDIU8cfdbc94e1ND5w8z0ftga203NXh71z1U//UY+wHDbNe8lV47BfD+kCZqwRuYWSxqPzyNQeDaD8R46FPcSWS2aZdUrTaoWtGRVzOjWMzPcXcH9yPSAfrpx1NXYGfDPYqsAYlWmpWp6WS5VHxykJtlABwrYqNYPnOc5yMrtQSId0jFmnBf789erurOXxqS3jlCKXk5bxvLuK7ePklt/BRv71dovs5D/damO9dX6npovN8KT5u0zx+JM2x5OnP2+SR1hLE8TCjZ/qpj50xhiqz4A6j259YkrJvE5CVZ5j5vnIRKAaNFUIdS1jmEa5F28DS3wxqOqanA7vIKrwreugOngHa5j5PlCXP0iKAXRZW2e+DeI4utbfc9wMGLqDZsWVPfqYWwgVIup9n0AybromLpl96AwvtIzFVVo1VBGa3oGEYYPYHZnNfhHkv7l/Gy70jsxqykCTOzE1++fCD/PN5KG6fmU2fW+e++fKqfv+dOjFVPBYyACG3WEpvrANYpIjpQqkc/9dvbw27nsumQ6wQtwF9nszUsMz3RuELkEl++B9+HZo0k/Ck5MQ0MANkEp5G5bXGSzE1+FCa0owH1rTG2pibxYv/RIbR9zF4I/FNsfKddgjzGd2WEyjU7damJZl4HaTqqkLe+3gYLrQZedoY+kkQh8dD0tuwLh2ofqXKOt3Fx3GxzyTVV5VvcWn6Own3CJ/S7fFT7klkusWlFSv9wcqr8nqRw9deupCG8raYPbS5FkrKMXU5I92y3zetLBU02J2VUaImmyJOwBhdo5KUouQEJKXRgdNiR5CYylPq2Co4BEhWCHEGeYNIe9+WC+9vym4hpuCpC8Q+owlPGauRspSAU3FIUVjdEl4lD+XOwu/3NjKxBBftT+3OPXuEKvCkk9oYlejMk/dYbOwDFhhiTGWpriMSpziPpGKSxAXl/nqFZTaRLrY95SorFeWOTDb7I1l4ZWmJMI7lPoQvydw5db+SNKWjGUmVTrVs9sbRsoxkeWZgkLz0ixjj4zEs17uIU3zuNdCmPMqKv+E60HCSikcksIJCS3lhIIn3xOW3I2V5iElorJCxyksM6dPy0QbKZrHknrC22S59tPuhH+TdGp+SIQfXh8L0VXmeP4dca+kUo5AnwUWzqONxZK24KwBvnE9vhhksO+nDqT9j6CL/a4+XsCcEjefS8ohkXv6ZvAdlmZKpnuBfnv0Wr6LNwyNDF2HcZimwmk85RVB6CJxIaP5fmVhmp3o+cz3kzlLpQnJD/EsGnf63qt+JMIpr9yeCHHNgrQnU7OGYeByGCJOZIaPdGmjYhpj5w4x6QJnCULBF2GYc5Lm0M25IPuAQGUN4s4BXq0FIUb+9fe0i8HfTzSl7YnQ4UiG90n38NL9ZDyP+kZTy5P3kfQ779ehqL/MTRy4OEUs+0DdYmjKj8JngpTYlG9k7inq6k7zAxLCXFDqZ0fDzWOh7FchUT9vLv8U/CQunzfwvPdepabeG7LWF2Wm7JDbm3MdC8WejO0OhXqf0tCCXVhaetwfIL+DD+MoyZDt2PzHeUxib3az91lR+O5NaMYfX46xieXJNSxlmn3vH1aKkYun5QvdrVEKuTWRRQvCkSNXZzINdVEodPqZeNqykOd/pVxjO5X6rsludG7ODJZaGEr4Eisr+ck0JARqD+8/aVHo+SlWYjCCYKAsCTKHHXsvcc+FKaRjfciFFNyjQ4R92XwVDqFfpcUL2yxOO5axdlY5dFXfKJlM5DhX959Ll+wqKhFmiVGZMasZltK60df8NA/p9D3Yp+4qoqMXJblHJti3RlRiqRDqcWc5WELXxWkluKhk8M00SYlSql+hcSOAc4T0XFimLOrbz9AydccHJZto+NM1T9kgfCIoq/R6TpV59UPDsJ0AIhIvnxDrT3aZx9vpebjC0s035tVPEx7AcYY66D4Tbt4yQP4KeG4Url7Md/19FNApgbNY7h10eT2n+ByF1+Sv3/U8t/vnsKxTViq/IlrP4uGevcZ0x5jCaMKpsbJOn0t1nq3nDtzKhuv5UImZ6cM1dE5b4lxg+m6pWX8k+tMqp8QHfW+wdpiC710fYVqMuJyoiw4pJ9v7XHqc+NlYACG7UYL795MXKIzoWRE7HU0czHrv69lAlZuwVzrmiMWyqqS8C8Ixw1IdjTpNM3vG0t482pxWMM9Zqdx///77sudkJC+ilCkx/pZdritWUuvJVVR+KGsddcyILa2pKWOmr6leRxx68lRbeE1ZrbnXunmCv88xHDhMh/IZuGvIh6nuhCVuJqDX9odPpyJajb8vfs4OYB5AH/RLxwcySax8ZaPTGXp9UYWxDVRdhXFPB6ymqAvtVROFkaLK4vBcAJPyz9vkfOelxL+Rjj2/9K793kjBq9ob1rdlLfXRfAf7+0LL/doIe7pZaveP3OeUR/q2q6ySz9E5dd/ZRfYottfhpebH0Sw/zV5EG6F5HqY8NMa9GSlVdiYpEIOSxXN7pDOTsYb8MIvPXpUooSVFw/I9YZjCVTmVK9h8sBcw1IGeQVFabb/sTsbewVSONIR4gKlNBen5CeSCxeyt8cRhOPPLebeh/gW9IrX98Wa08+m99V60t4g+11K0WTWEoXPeWW/UF8ZIxbBYnFu/xBkJOfbQfuOs0I5AIOl45sxeVp0N0CfQFNLnehbMh1Um65FHEx+J9Yjt6/vK10Sy7S0ZIZb2PPHOIPWtfz2Xxv1y5Ym2wtLgBWl789LvktD1dCko1DsSdHdlH8/qX/b+IelWRJLK17cn7yaYKikv5VOxzJ45Z1ok3ybk9IxxtOLXc9NOfaEPkc66CPS/QG/LXevgmXv0eTmVIjN3bDF7Wnaqrr+BbHNZz1Sx+7xqYrpdC1Pc9YaM3VH+GLtRDl126sMFL8pwHilN7VmBOXlz692ByteHYp2kBZaVuiKTFMEZfMNP55wof4bpkBrMB7WTeJeBn9L1JaXXdxv1n9Eng3NUoaFKmkpTwIn+3pwHslaibwUyTV4J+NOKf3ny5ftjaJMgugqecZMZptCBedxhujOTlqKdqW3tYJSRP2tn4r9vyx7c/+SUSZhVTko0+vl9SshnygYZIRIFMkBT1tSFSNJEg+wkyWq/C+v8m9TcAw2JPVXUXhVWFkFWEGVPe5UzfIUFfJv4GYDPqCYn9NAe/JKz57tXfoLP6XGhTehGWUk9kSo8f73u0Qtp+TuQIVsfc/z7pcnOHehj0tbMC2hXhPEcJLEO796jzRzLmyG/BB1ocJ+cGeoefopPMSU7LrQK9sc6fy71Z2xug1RBWT6cAhmyjyUxOyDzI//L4iWo2y19P3x4BgNtZJfO8cvDJHyYn9J99A2GWiRkRdgTJBQ45s81MdwCwyna9gb0UaJzYmgG2rpBF8iUCbNCUUgq+k/1L5+3ftUmS2Vklr/CJcA8EzrGdI9x3MF7kDoqH88QYAOK9ZHQL4C4MibCL2BoF9HD2il8QixlXwH2oQBHEfvcMScYci93SVjUos9aK5SrY2UCcvpIy0v6/WOK2vg1ffVT6G8shvdsPy2O0ybh5jdsoKRv1B7YDGy9P1HSq9B3kNDjrso0/ey7cT/avr0Y7ZN4fqRlwLjdMzgLi+34vg9xBWPAtIQoS6AdpzF/vyrV1KA0nIOZIecY7eP+YJbtw1WJ2WAP5+ilMV5KbNvAqxFTSsMqUeZtf9Sk1oaFs97Tm3h27WbT9mlmjj2C5UE/atjX96u5SZSZLS7TdE85u/reUQltYSrZWKmOFP3fKMmSY3+MfVD+wHT/7BxtywMMnwUeDLrvQQe5WsGzA+WwFtGvdiT0ugU8G3kVjB/1D9SXM+2JuSFydA1oWjP+HUsSIZ/EVMoGSVc8W6d1xm7mfNz0IeG5F5TQis0hyn/zo+U+baXnZnEbN8ZAUhwjLgT0+LtpQ8noU2pvay2BwVIMpJzmhciTheuMZ+tQFUZyMd35uCoi1xPfWGZ5gk/NQdyuQrCKRPbDVGI2nO1AM1heMbBjBaGOaOM7knR1/nUajilvSHiliOc/YhzrqN8ebtOvPKcyxJMLa4B6ANqHl4Rum8F+GbiIB4H3kr5RXQPpuuMZSh1kXiz/vp8T2m4Jy1gfz6TPLW9FbOd0vZBuNt07eEyaNpCnpuTfwnW9p6ygORI43cdz+bpbH9eAzDnjHVI28oTc073aH7fkjeLyTnmy2Gd5H/afyDA+5saXc1EuBD6NobhYsjqwxWXIvJ/hgVfyavj+P0lBib5Qbl4n1y8H95DaH5ralOtaUxtiKn5Z9dAmoAyL6efT+Fd9Scu30HW8U368p5zCDRngnpKEn8be3pB1CnG5dP4+60O+kkcCu+dXfJmZ47wlx6bP9sI1LNAHG7/OvtXNWFuixzF9SV14qtZ4Yl7dektWteZgIT7/QTa39FxEpX5a3oWU3tUiG20KL0PKP4a4t0w/eKhTLTBGAkvgxjEzKftrkQ5dWDYo3baPEwm/9+3OyXSm7tNeaqQxnzfOCordQcwoQ32o2G9SJtifE56mxSWpwm1zPN65mBYCU9RKzzFsP0vT7A7L9SCm6hVTFt3CkFiYUqONJd/g3CnLa5I65lnaYJrjcL3UOE6BlAW5YIr7WLrgzLWlbfulKIIYi3z8SPq7zPUt4oXX/V3MMPUHrEtVagxchwvnth5PsSG9Z58TEZayfrQY9kLiyO6xxyj1k1nu9y3OIjFOL02Mx6i/nqoyyFF9xB1vpNeX/aJRH8A+fcO9OspMf1L3sLxSYBNJ2YioPnX1LvTtbVjEYiBGAObAfc0qY03TbGXZQvPPJCqzAx8maZuu9IBQx0M8fLq/MM/p+wkO/Pkp/33BvJ/98rKNpxrivxFrLi2u5tTF87/TkN6dMtzbxhTPlRmVr9TMVC85frE8m7i7ktSZU/b7VGYw1ckVjU7H+xSP0ISbWJgMGZ6mKhRfB+rHQFP5rtZUZ7Kn9eSF1xs2ntZyqzlDfxqWtIS13sL7TlZ7MDNADsjiP6FPE/YMyCK7X2UfTZWG88tYQP/G83fdt8tLuNZ3xhRhuhmNE8+mO1tI3j6JkRYRU0tS0dydZqbQTt2k+rOJpcqbJJWMl5uW6neyL/+upaWa4kCBc0sSRU3WNFFqzsWhWBdVr/f7lbuMl3q7nGIpwGN4mOgM99NQnTJSPC1+i3CSGOsr01JJaVxfVDYqxLGmy2tGKSxvpOguxGWSNE20v2Nm5nB+P9vxPX1fWZaXDLx4RgnQvFJcxTjHcD5QRu/weWP3Y6zmzgj0l1GUHtM5E3/12VHqQkYZlpvY/zBeMYF3BZ5Zll+wVE7Qz6C00qtbOzqsXFcXtqiJQkdtM1WHxXSiskBLLgmPybhhXuiW/XUiukg4hvxSUg3Q88e9+0ptgJyFsiCsR+L/PLsljRsKU7Wn0sP17ipDlFvuqN05mhRDkFHuKHxnwfMJPOvZ5ASSwh7OpHdbpGUuME6006gcInyotOkuKP2DPNzUR7CvRx8YR31PCe8ied0voy4caSmpD29SlmnpDyI7Dw4BDrlLyoj3sYT4gZZPv7tPs7dL7aaN/b4+JEvNvwS6NcqbLW05GWP55Nkmq6z7TRsKXVeUMUgOBL8ME5ZpWHQD7LBS+ezYs87UiBeSWITC9+7wrB2sPJJ6mZY15Uk5eyLrr/7weQh43qG7BDkSZLh7351Tpi4qN5Y4ixBD1ryRkjaj9Es+n8g+03PPyA9i9wW+juVtYBzUtnLNzzPPT5T9Nz4eIDv3QKhfgszHiYuwdBKMJdrzJ/QHEtsslqUwwljLePuZ58Hf8Ayg84S2NdAzebMlzLPxocnS5Kg3hhhaNpEONR1fHaZRdM7XJYM/W4qN+DCfK7Mh2oM1P3Wll1xrH8sJfJoNbUzku7Z8DMrNF5UtieYhzIXxGHsW15MBWYPqY20mNV4Zz/x7SkzdUxIlpLeCcoN7qrPG0nKHfquYrB7L6RGUZ3xpdAYDTX5WkDc2PpM+eF9Xm95UW2iKynhvwxVzpPZT9ehwsXlHme4zNpxm4vwn4wn4cqzUGykVCHzCLwNH/Mia1pxUEA8P/UP7zbsff3mk8y1l2TeFwlwBjXkgf6zjeVB8HSjwM+Dcb4Cf5pZnvK/8lV/+OWbTySkBniw7S/3Ov6GfkvhHNFo2cxD4OWJxxxivn/TFpPlbMd2Ssmct4YC2jphslpybhYwyERNi90E/JLllntdHoJlYimuY+9V+MGQ76tQvCegwoGNpwghL9iJGDL6neE/gWQbF5BWUAo34kt/HfBn1rpKRYQ6G37lksa9PivW6inENLuiYiJNrfnQURlRBl+6Mnn7hO9t1drL8wDxG7yZNA3uFo8/hi2F5CcJHm2kbPsbE2Z79DDTNaSS2LYa9itFY+H7iF5cTPsKvtZHwIZ+z20jnOQjz8ETnf9rfg2fVSh8PgCb6pL0pKREpXdkAs9pK4KfR/kv7cqHtMfc9H8a0XY8pZz5CGdWf1xjG8e42eqjnvyG/gDPWbwdjTRagX6Pf+JIxnpBXD0nMXVguMDOHQC4vE0FX1xL+sN+kJub2iX+noc7nTUZsTO+Ll96mfuioJGChLIe5f1izPfhErMhP6O4F6e9/lfzml+QIcuSgPc0vt1fBnE0+b9TCsp4q5nUrKJVNSmue7ys9jLwX9akcncHPb/e0pnPjx3/EY9PJfOWlf4d71ais5h3tn2OlTenzGmnPs2gpO/idyfQvBfnvXgIaIXMlRfIVKdWJso2s+NdAt/isr8oGGRV4A5YeoG0c6FrMvhwvT+NXgzHyVBf3SHlbUtbQ7zexVXS9+tksIzZY5oektDLB1IU60ss4bIeWAFWwrPmTi3Gw5riXKdPF1uIe7MPVuG/gGr8wRjzPOrDHOufJOItmvtLvoB88yVETYF/T50vBO8pGy0P/rJ9TUTtTOh+sw3xk/rz4OrzqjOse8QdRfYGO2eVF6pvtzJ2suIefHB/5BKUxsvqDPrNkf5AvnEnuK6K33NunG/uk4EPthYg1I+fPC+1fhdJTk5RfCOf4VnmM7P0W7H+UPTt+/iqCbTOlFfF97vCsVFviQR99UMwG20HdAPQ4UqIGbWi5ZSQ+96ljLoj96Nwh/jASJyJiyQlt5591Y4uUr9TOMH6kyzPJnTUUsK+wp9m5tfKUaCwdUlad+HhHH+i/HcAZ75m+/JNoA7EEX1ifzH2D/EPbuSZJ/99XgrIfxlj3iOxAsYOJft7E3ubMF/HJR+OI5zr7Ai18gX5oPyLZZEnzdER96sDahPLmdbmNr9BsbOxGYKvAkraNRXg+BzbQSEZCeyb0424edmuucVy+bbylYc6y2NzTc4bi0L1ob3lAi77tUic51/C88bFPSiinXWOhafnhwljPW5+vPndHjGOAOUxh19FXNSDrki+vfnoNvjx+St/oF0QbcBD/iL5ZGWgTS3b1DhiX/9K6FQN33ydGh+l8Hwl6iMreIA9DP0aP/N4TmT8BH6RYdo/J8luk9pivh3nkOeA7LPBQTc15/hfPYxzvE50N0I8MH4HPk1foSyK/n+jYqb8guxxPPbWH5keQ6RrI0+FsCMcI7yP+B/L7pU7eYwfvzLD5f3n8jWivXuug13NAy27P/9h+3sD2FvE5aqfYZcaG3/pkxXQVvCsDx/WT7Ua0mcDpf46H3tOvOuatnBtZGK97+v2J/FSkFNfCm7y69fGpKq+Rj+gE205wDhjL0Y3ZLg5ZOPg83TfNpzCeVm95JAaf6Kllkiv7N+n56VPYWYIrxTwK0Fcl1ibi9eF3T2ry9QEzw3HsQTfe2m0NztIPHMuQlofaHzG3DeynNZZy8mOJiY6K+R2kloa2EY+Uh4M5yNcniXz7HrftDEY68NVOGJPkyytF8zA2kM8qc1qWHvNfuPnn9YvCv1m4/xcd/gXvHVZmBuanbAnE7pTKMZ65LpP4+xka/xDl9uHr5mqxzowFv7Eu9EPihDYm6BSUjkj8Nc79gcRsYnyQUp8bZZklsRuIi8P4g+KcLWmeGI9zip2z/bq+wrkJYzl8PPigQBbM34+FMQo35FlCo35pWjoP4s5EfFcLc4WQ+dgEMS1EbgdafmmZz8c2/i0crQbbgv24w/3ox02hvppPi7fm6YZ8QuIEimwIn+ApUR5U/53P9+D0Er6DYBw5vs1fUZuAxFsM1N2rJbtsi+IavbfhQnv9VK7W+3Ov0piqeD6Ga0xVBh4tx/56Gzce4rRozuqieNEw/8O1Py1pu12aZbS1wD5uzIlPa+KPBW05cDYATfFeKLO1e0m+npn3N3ccwBc9zHNzgvd5L0HbjcXGxzhh3uSC3Cnh+FO6UzjXBz9PxZvuzv36CYNP56eXniuYt2iDMaF5fCSYX2KDormmSYyqL5//0n58zoYa7jeiJ94u6Zj2eWTkZy/EIdAY30SOiVgMRSjn0horOx/jjbkm+jBmFs/XPAzhzfyxrSgfDdUVcvLLp9sUgc5GJIfoIZ5/Wx7P5xM4V/Tr3Bg0NgJzXDafXFM7Va0yye39JC3Z/fh5c7HO0g6vGeKpCnKI9brqX9D3MGh01snv6kIM00Nyg4Out6d7ojLTYzmS78A0R7iR6LkgfjScX6Ajkn95OIK5R/ngUsi7r7Aon/FXSU0d1kjfwDrl52D7ZA7pQvootjXEsNI05/qNGh/pfHC3eR3NYeCXZ50nxhxi4Ru/ALOdh+8635Hz7r/JfAe5fT6XwycbW/Ir5AQiL7L1N5BBWiPEyf9qfPz9OPAbOPhb+a/Ddmgtj09jZcg4P7pu3UDsN5WfQaeDdUI7D5yLJ9C9N/pqsde0Tg/6xlpnzLnHzPycuhjfuiOxFKjfAV8y2z2aI0ok+epBxxNQ3qQ2k5Y8d1bqzOKw1K+2mawycyUSWQfOpx3mHkAc3puCea9sEvdB5df5JsiPP/B90dZlfexywgn0QKu7CvrtWd0lnOlKbf122cAz8q6r7efd8abe1dan7nCxHyu748tQIPnajbNgThS2OlBYo9dgeLiWExNC43NjfTzE8nPmYkXvjQGKaKEPOpt4wFLzqNvG3+fXuSjE/sJcvKM+o4uwPqiXwP+Gwosw/3OrpTVhLuehLTH2rs/EKvXcykzjvDPKWnZ7g7oWyd1ocALWYzuYLeESloNfop1vR+qBdf0cj0FpZcT4TUK7B+KzdM9aZeRgC7EQzdsYQlo3zM8fSTEMEW6wfkH8AsEHrkjeKlL3DWiA6yksyOP19USpfHQ57PP+8gY6u/nMPibmtJ0T14W6mMKHuIXuAv5vzFyN1JVh65hPgdb86gT4ELQxHO0Gm4x7wnpYWTF8GWsRYjjKT/l4tyQWEOfwRuxE/1SAm43JdE9rKvOfAp/VnTECZC0JPhLpW1kE/lg+qOkTi6nAvoR4S99vKl5CvKWPTXnJjq3Pjsl+7h0kcbPx8xdskNfopHaDtsf8ZcB3z2bvdYG1ufQzzTWqEZ/qaYa2Jal5fD62+AvqGxbBqhPbQ8Qjvf5bVj6BdOwSsWkS3GdxbALWLPNj7uGsBhpciqi3r1/u8cVd679IJxSbmhMbEsRRUczFp+IRMvdEQCthnFMrp+5ADgb7hepzO1+v29yBP40wZlk1OUI+69eQ+Ky+k8q1bvh55uM4o6zaS/59NA8/Ocd4FdreX/lz/Bhj/x6CNZqAroDr44wE4LfqYbJUj1Kyfldw/1X8eOKZFbML1gz6v4Nx+NgrHvgVD/xQ3Ywuog20QeLLXxrWnzpnD/1Zd/fRfgf+qCxwDemZTjEJZK7DdhHnze5t59zh3pSO0L0V167tPsbDnY9pEfcWsbdNYnr9bNVxLaSNcA2Av55Q1+qR3CETPKvdEDv0/LSj7Sxmr26du8YaRnTrr1sqZr5Jc382xMw5wLwARdcJ3hhzB5BaYn6dtquaXfUCG1dWbZZwr1+wnsqbW0/UE3tpdC7BvXGMci7WkZ6jIf5BV8P46N8y4jtq2nMlptug7HGaaXDeo7xRGJfYIvVjCT6GtIcYeuDBJGZr3NmA7rxxltrbZLnxiD2gBTwize+jfZBzBpL+Bmcg0AfhJxhrEMTnhZi+F9ofmGMN9BdhQfIPeJoqv8/w7J5bbfTL9H1/oUDPMdiLUV1T0AVWzH9k1pvebB1rvdy4npNTAZzcZTuecVb2xjar0H141844OrKzO3j74Vrzq4Dfuj9xZ165aVrW2+Gr1rRiVUqM7XClivVolIxymS/xVYc1rantVCrmz5T1FvDn76CwN3tV2Dv5RbqQsz89X+lZ0dTEpoW5uhabkoxFKx5sdgXz2CDjA8T69Z6x2Tl2a7s+bEi98T8Hl6OK57FK5/50VGy2XDZ5vsSZglmqVCpALZbNlaxytVKtOAxnCeX4dHz7y8Ehxee/Mf5PKeOf4CfxZO5ovzkflnewHXG7Xrbd3X69PWfsh/hdb87KdlezrLv8wu3flPVq9qAs3E2iDzOcHbw8GfYe8JatAwPa7RM3Gd7JOO/kwyqr/a2xstfLJ8sv/X513VqvrMMWlz3r6n7rgpS0vaoHnypB/23rnIytTfdSha09Vh3nsWQLVaRYUygJRo0vObbB1yyuwtlT64pi6eqacKliGZUS/2ixpUq1+lgyHd4qGbbFO1PeqVar/NWjPkGzLPc5eiXrs4NpSVIf/vz134oGC5x1CbNKR2uy5qNTMe1SzS4LpQrLQm9rglFyWN6aCrUyW5lOc0bLV6cVhxesEs87VqliWgIMVKiVKlPO5FimZj6WjbzRVhj21402Z4/uDialm5vL7xNxFs+wnZ21dTc++WXdsXWmDtCf5Vy9hlxu/PuPHyPgLevT7sePnmtt17v1dP+93xz++CFu4cWn9XZRrfz4cax8Z76XmTIr/Pix3Fnrreea323Pu+bbX2tTOe/2zvJ739l/b+/3m9+haWzxxqFgnvdOY20TlpGuTp9ZsX4B0keDJ5GONyvan3kikVnZle2JlY0iUDdhBNSEwwxnPZIRBaRkguCC64+/2qKqMMKrvPDamtapE+/uL89q4g0Q0QDadR/nyDizgwGM66X5cQRtcWe0BESWHHWaGRWrg7ySzKicdoZ7O2pkHY0ss21i0UhEI6WriEvLePtSYt7UlnAmmfHHxOq5oRll0JoEWub5aY1RQOYSsxUO/OyWmMXy6dx/Vy+vWf0h3lbMnh5K8CTqkPTjXeL6w15FiqrcoFe9rjYXMw3ea3EEtbZWRsyMZreol1HrwkxBySicCmYbxUrzKOWGiJwJ3CetJh+Se1e/khG1qNk1OlxPkX4pXSU0+RZ6FHszuheEg9leBBFEQNOkUlZC0g8japqJSKaYdSSKEvQzTYsOWkFgvC95lnQxFu30mWzeSEsuRXvm0VPKSkOy4Vmff0eGdn4jkyRWyBunvdmZXs1YRCyxMvp95EEzrO8IcqDRsSSXVml/UXKsGil0yzXy5553P7kwF+8wF2uzDHSZUS056eWoN9F6RyxZ6M1F7yvxUHSA/udHEzT6ro9Ko6i2/Ryzj1pRZQuCUjN7rxxazjDbVs66kYoFtJpQZxVEiBFtn9l7jjJzaXXxZOVs+l3HTqODX90nV4ZnJXHDotdkghZuV0rT5NcrQaNn6DMoBprZF3mrpi5OM0TtWb7FX4JzDJG/ktg52oS3Yp/FPVpFJ0uRhXnPQ4XFMjfVN4G346eiDDnal3zkq5+hGOkA19ZFPttX4xm0/aotrj56fN6v/CzIfkbjKLofM4SKLFoq/czKiB7b6SM8g0h1lKLKV29Gi/fQKwZnGlZQ3BJLwtJDzweeLWF1aD/7cZCpeWuWEfG4Z3KzHftoycCSkYwu9JEu1JK+Jvv1cxaOYrRo6L2oX3RaFTJv3YnME4v0DD031JNRxzMnUZnLSPB7foB7P7D8B7QDaxaO+0blsYGFqNMlyS7tUlqwPQPlpXYdI2DncFave+9PmCHMjyjt5UbmxaP5ZThX7XHHy/GcFEXLYL9Ea6kDT7IvsHd2OvAgv9oc8UAMOOhXXvbvvCp/izATIeFdfuZ4H6Frexa338CYPb3RnFXWv+0fH923nOwFWRk778z+dw9vCbLxwXiVes/kMBJJOIRRsbCvukv0lKHM1V/po05mRZLYXEAbtmitOkcLMwsuWIy8fZdEEhGH7xkanHcC+j9bS+H86tYf9fHsEM7duKiKKd3DvtV8bj6vZ/JSWxPkaXzdlPozzjlWgMLMjcQ7hNnXSTQb8gmeZMyWWpfnTVtbfnptvf4RxsfHsk0imgu97lvo18EOUOapqq3BmqPMiPLjBPkC9rncB7lPgPNV278oOVkRU2f4FFHRxNp6FYEeWuFJ1uQEam0jXOnON62ity2in7GG3mUJ9W0B05pZNYTatGSBZl+qWI5TMh3TKZXNSo13yo/TqcF90cx3Zf38ezHz0V+C+6mljt4SfOVbWhKGgbhNcONsl+5+79jqzjdSJd4eXo69PX6dTj3jVASzytlopaqVKlW7WjKqglWqVTlWKD+WHW6amPrQZDfADj805o61yDEcXtnT3BWxCWZdWlKtnklOHxk/vuyfyPT82P5Y/dNfEm/bOjPno/mx8VzL3TeMzf6wzWzfW1uGb4VJvMOdrdZbp77eP1nW+kDMgGl7J71FWu2d7crwMm7YrQ9bar9hU/O/c3f7BjbrbLM65d+By1dwl2XsHMVZ7dy9e8wc28xbm4bXWK89e326GuGBtJ59LTSw/hMxrz749tWHf5msD8OD6Tz0DjvX+teUUdZY7Yd0f4W7INto/UsItDqtlu2p4JRszrRKlYphlgweuIQgGHZZsDhQGiqZBAp8ytk/TIa9P4A8t/iu/yHM/1aEOWUYCzgkU3IcwShVOIcBplm1S5ZTNk3ukbN4+zGTMMmI3NV0/XnCTK/wLbrcwavwTYRznubGHr8gf/huj/Bv/OV/CPj/XQKOyyvfekA2W2O/hkdzRBf3S+6diMQX7oYO/F/gXQ/rlXf+1z+ADe/gtRFFp92J/0PRfx8UnZJ8T465W1sLZ68422OKmqOLDc9FdpW4uHeXwf34Dd0q37ANunpcmX7jfGzWW9gN6IzGEbDfme++zPBt6a7c5WGphQ+Rq0zJ8DZz4zsL++Ov/z/HgSoShWUBAA==';

const IMPORT_CODE_ENG = IMPORT_CODE_DE;

const CODE_META = {
  version: "v1.2.0",
  date: "07.02.2026"
};

// === ÜBERSETZUNGEN ===
const TRANSLATIONS = {
  de: {
    metaTitle: "YouTube Music Songrequest für Streamer.bot | Twitch Tutorial",
    metaDesc: "Komplettes Tutorial: YouTube Music (YTM) Songrequest mit Streamer.bot einrichten. Kostenlos, Kanalpunkte-Integration und Spotify-Link Support.",
    metaKeywords: "Twitch, Streamer.bot, YouTube Music, Songrequest, Tutorial, YTM Desktop, Setup, Deutsch",
    
    title: "YouTube Music Songrequest",
    subtitle: "Tutorial zur Einrichtung via Streamer.bot & YTM Desktop App.",
    
    sidebarTitle: "Tutorial Schritte",
    steps: {
      "requirements": "Voraussetzungen",
      "ytm-setup": "Setup YTM App",
      "sb-setup": "Setup Streamer.bot",
      "spotify": "Spotify Credentials",
      "feedback": "Feedback"
    },
    
    reqTitle: "Voraussetzungen",
    reqText: "Damit das Songrequest-System funktioniert, benötigst du zwei externe Programme. Bitte installiere diese zuerst, bevor du mit dem Tutorial fortfährst.",
    reqSBDesc: "Das Herzstück für die Logik und Twitch-Anbindung.",
    reqYTMDesc: "Der Player, der die Musik abspielt und steuert.",
    
    ytmTitle: "Einrichtung YouTube Music Desktop",
    ytmLogin: "Login",
    ytmLoginText: "Starte die App und melde dich mit deinem Google-Konto an (oben rechts).",
    ytmApi: "API Server aktivieren",
    ytmApiText: "Gehe oben links auf Erweiterungen > Aktiviere den API-Server.",
    ytmApiWarning: "WICHTIG: Stelle die Autorisations-Methode auf \"Keine Autorisierung\" (None).",
    
    sbTitle: "Einrichtung Streamer.bot",
    sbImportLabel: "Import String",
    sbVersion: "Version",
    sbUpdated: "Vom", 
    sbCopy: "Code Kopieren",
    sbCopied: "Kopiert!",
    sbInstr1: "1. Klicke oben auf \"Kopieren\".",
    sbInstr2: "2. Öffne Streamer.bot, klicke oben auf \"Import\" und füge den Code ein.",
    sbInstr3: "3. Gehe links auf Platforms > Twitch > Accounts und logge dich ein (Broadcaster & Bot).",
    sbInstr4: "4. Aktiviere im Reiter \"Commands\" auf der linken Seite die hinzugefügten Commands.",
    sbActionTitle: "Actions Konfiguration",
    sbActions: [
      { title: "Action 1: SETUP IF DUAL PC", desc: "NUR anfassen, wenn Streamer.bot und YTM auf verschiedenen PCs laufen. Sonst IP bei '127.0.0.1' lassen (Nichts tun, Finger weg)." },
      { title: "Action 2: QueueCheck", desc: "Zeigt die nächsten Songs. Tipp: Du kannst in den SubActions das Argument 'maxSongs' auf eine andere Zahl ändern die dann die Anzahl der Songs in der Antwort ausgibt. (Lasse es zwischen 3-5 damit die Antwort nicht zu lang ist.)" },
      { title: "Action 3: Song Info", desc: "Gibt laufenden Song per Command aus. Gehe in den Reiter 'Commands' und stelle sicher, dass der Trigger-Command aktiv ist." },
      { title: "Action 4: Song Request", desc: "Dies ist die Hauptfunktion. Richte hier den Trigger ein (z.B. Kanalpunkte Reward per Doppelklick). Du kannst bei dem Argument maxSongDurationMinutes einstellen, wie lang Songs maximal gehen sollen beim Request. WICHTIG: Hier müssen gleich die Spotify Credentials rein damit auch Spotify-Links beim Request funktionieren. (siehe nächster Schritt)." },
      { title: "Action 5: Song Skip", desc: "Ermöglicht das Skippen per Kanalpunkte oder Command (Mod only). Trigger nach Wahl hinzufügen." }
    ],
    
    spTitle: "Spotify Credentials",
    spText: "Damit Streamer.bot Spotify-Links in YouTube-Links umwandeln kann, brauchen wir einen API-Zugriff.",
    spBtn: "Zum Spotify Dashboard",
    spStep1: "1. Logge dich ein und klicke auf Create App.",
    spStep2: "2. Name: z.B. \"TwitchBot\", Redirect URI kann leer bleiben.",
    spStep3: "3. Nach dem Erstellen klicke auf Settings.",
    spStep4: "4. Kopiere die Client ID und das Client Secret.",
    spStep5: "5. Gehe zurück zu Streamer.bot in die Action Songrequest.",
    spStep6: "6. Öffne die Sub-Actions und suche die Felder für spotifyId und spotifySecret.",
    spStep7: "7. Füge deine kopierten Werte dort ein.",
    
    fbTitle: "Feedback & Support",
    fbHelpTitle: "Hilfe benötigt?",
    fbHelpText: "Wenn etwas nicht klappt, komm gerne auf den Discord.",
    fbHelpBtn: "Discord Joinen",
    fbSupportTitle: "Supporten",
    fbSupportText: "Gefällt dir das Tutorial? Ich freue mich über jeden Support.",
    fbRateTitle: "Bewerte das Tutorial",
    fbThanks: "Danke für dein Feedback!",
    fbPlaceholder: "Was hat gut geklappt? Was hat gefehlt?",
    fbSend: "Absenden",
    fbError: "Bitte wähle eine Bewertung aus.",
    fbFail: "Fehler beim Senden.",
    
    relTitle: "Das könnte dich auch interessieren",
    relSdTitle: "Stream Deck Control",
    relSdText: "Steuere die YTM Desktop App direkt über dein Elgato Stream Deck.",
    
    navBack: "Zurück",
    navNext: "Weiter"
  },
  
  en: {
    metaTitle: "YouTube Music Songrequest for Streamer.bot | Twitch Tutorial",
    metaDesc: "Complete Tutorial: Setup YouTube Music (YTM) Songrequest with Streamer.bot. Free, Channel Points Integration and Spotify Link Support.",
    metaKeywords: "Twitch, Streamer.bot, YouTube Music, Songrequest, Tutorial, YTM Desktop, Setup, English",
    
    title: "YouTube Music Songrequest",
    subtitle: "Tutorial for setup via Streamer.bot & YTM Desktop App.",
    
    sidebarTitle: "Tutorial Steps",
    steps: {
      "requirements": "Requirements",
      "ytm-setup": "Setup YTM App",
      "sb-setup": "Setup Streamer.bot",
      "spotify": "Spotify Credentials",
      "feedback": "Feedback"
    },
    
    reqTitle: "Requirements",
    reqText: "For the song request system to work, you need two external programs. Please install these first before proceeding with the tutorial.",
    reqSBDesc: "The core for logic and Twitch integration.",
    reqYTMDesc: "The player that plays and controls the music.",
    
    ytmTitle: "Setup YouTube Music Desktop",
    ytmLogin: "Login",
    ytmLoginText: "Start the app and log in with your Google account (top right).",
    ytmApi: "Enable API Server",
    ytmApiText: "Go to top left > Extensions > Enable API Server.",
    ytmApiWarning: "IMPORTANT: Set the Authorization Method to \"No Authorization\" (None).",
    
    sbTitle: "Setup Streamer.bot",
    sbImportLabel: "Import String",
    sbVersion: "Version",
    sbUpdated: "Updated",
    sbCopy: "Copy Code",
    sbCopied: "Copied!",
    sbInstr1: "1. Click \"Copy Code\" above.",
    sbInstr2: "2. Open Streamer.bot, click \"Import\" at the top, and paste the code.",
    sbInstr3: "3. Go to Platforms > Twitch > Accounts on the left and log in (Broadcaster & Bot).",
    sbInstr4: "4. Enable the added commands in the \"Commands\" tab on the left.",
    sbActionTitle: "Actions Configuration",
    sbActions: [
      { title: "Action 1: SETUP IF DUAL PC", desc: "ONLY touch if Streamer.bot and YTM are on different PCs. Otherwise leave IP at '127.0.0.1' (Do nothing)." },
      { title: "Action 2: QueueCheck", desc: "Shows the next songs. Tip: You can change the 'maxSongs' argument in SubActions to output a different number of songs. (Keep it between 3-5 so the response isn't too long.)" },
      { title: "Action 3: Song Info", desc: "Outputs current song via command. Go to 'Commands' tab and ensure the trigger command is active." },
      { title: "Action 4: Song Request", desc: "This is the main function. Set up the trigger here (e.g., Channel Points Reward via double click). You can set maxSongDurationMinutes argument to limit song length. IMPORTANT: Enter Spotify Credentials here immediately for Spotify links to work (see next step)." },
      { title: "Action 5: Song Skip", desc: "Allows skipping via Channel Points or Command (Mod only). Add trigger of your choice." }
    ],
    
    spTitle: "Spotify Credentials",
    spText: "To allow Streamer.bot to convert Spotify links into YouTube links, we need API access.",
    spBtn: "To Spotify Dashboard",
    spStep1: "1. Log in and click Create App.",
    spStep2: "2. Name: e.g., \"TwitchBot\", Redirect URI can remain empty.",
    spStep3: "3. After creation click Settings.",
    spStep4: "4. Copy Client ID and Client Secret.",
    spStep5: "5. Go back to Streamer.bot into the Songrequest action.",
    spStep6: "6. Open Sub-Actions and find fields for spotifyId and spotifySecret.",
    spStep7: "7. Paste your copied values there.",
    
    fbTitle: "Feedback & Support",
    fbHelpTitle: "Need Help?",
    fbHelpText: "If something doesn't work, feel free to join the Discord.",
    fbHelpBtn: "Join Discord",
    fbSupportTitle: "Support",
    fbSupportText: "Do you like the tutorial? I appreciate every support.",
    fbRateTitle: "Rate the Tutorial",
    fbThanks: "Thanks for your feedback!",
    fbPlaceholder: "What worked well? What was missing?",
    fbSend: "Send",
    fbError: "Please select a rating.",
    fbFail: "Error sending feedback.",
    
    relTitle: "You might also be interested in",
    relSdTitle: "Stream Deck Control",
    relSdText: "Control the YTM Desktop App directly via your Elgato Stream Deck.",
    
    navBack: "Back",
    navNext: "Next"
  }
};

const STEPS = [
  { id: "requirements", icon: Download },
  { id: "ytm-setup", icon: Music },
  { id: "sb-setup", icon: Bot },
  { id: "spotify", icon: Key },
  { id: "feedback", icon: MessageSquare },
];

export default function YTMPage() {
  const { user } = useContext(TwitchAuthContext);
  const [activeStep, setActiveStep] = useState("requirements");
  const [copied, setCopied] = useState(false);
  
  // URL PARAMETER LOGIK FÜR SPRACHE
  const [searchParams, setSearchParams] = useSearchParams();
  const urlLang = searchParams.get("lang");
  const lang = urlLang === "en" ? "en" : "de"; // Standardmäßig 'de', wenn nicht 'en'
  const t = TRANSLATIONS[lang];

  // Funktion zum Sprache wechseln (updatet die URL)
  const setLang = (newLang) => {
    setSearchParams({ lang: newLang });
  };

  const activeImportCode = lang === 'en' ? IMPORT_CODE_ENG : IMPORT_CODE_DE;

  // Feedback States
  const [rating, setRating] = useState(0);
  const [feedbackText, setFeedbackText] = useState("");
  const [sent, setSent] = useState(false);

  const activeIndex = STEPS.findIndex(s => s.id === activeStep);

  const goNext = () => {
    if (activeIndex < STEPS.length - 1) setActiveStep(STEPS[activeIndex + 1].id);
  };
  const goPrev = () => {
    if (activeIndex > 0) setActiveStep(STEPS[activeIndex - 1].id);
  };

  const copyCode = () => {
    navigator.clipboard.writeText(activeImportCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const sendFeedback = async () => {
    if (!rating) return alert(t.fbError);
    try {
      await fetch("/api/feedback/ytm", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          user: user?.display_name || "Anonym",
          rating,
          text: feedbackText,
          lang // Info mitsenden, welche Sprache der User hatte
        })
      });
      setSent(true);
    } catch (e) {
      alert(t.fbFail);
    }
  };

  return (
    <div className="max-w-7xl mx-auto p-4 md:p-8 min-h-[85vh] flex flex-col gap-6 text-white">
      {/* SEO Komponente anstelle des useEffects */}
      <SEO 
        title={t.metaTitle} 
        description={t.metaDesc} 
        keywords={t.metaKeywords}
        path="/tutorial/ytm-songrequest"
      />

      {/* Header */}
      <div className="mb-4 flex flex-col md:flex-row md:items-start justify-between gap-4">
        <div>
          <h1 className="text-3xl font-black tracking-tight flex items-center gap-3">
             <Music className="text-red-500" />
             {t.title}
          </h1>
          <p className="text-white/50 text-sm mt-1">
             {t.subtitle}
          </p>
        </div>

        {/* SPRACH UMSCHALTER */}
        <div className="flex bg-white/5 rounded-lg p-1 border border-white/10 self-start">
            <button 
              onClick={() => setLang("de")}
              className={`px-3 py-1 rounded text-xs font-bold transition-all ${lang === 'de' ? 'bg-white text-black shadow' : 'text-white/50 hover:text-white'}`}
            >
              DE
            </button>
            <button 
              onClick={() => setLang("en")}
              className={`px-3 py-1 rounded text-xs font-bold transition-all ${lang === 'en' ? 'bg-white text-black shadow' : 'text-white/50 hover:text-white'}`}
            >
              EN
            </button>
        </div>
      </div>

      <div className="flex flex-col lg:flex-row gap-6 lg:min-h-[600px]">
        
        {/* LEFT SIDEBAR (Navigation) */}
        <div className="lg:w-72 shrink-0 flex flex-col bg-[#18181b] border border-white/10 rounded-2xl overflow-hidden shadow-xl h-fit">
           <div className="p-4 border-b border-white/5 bg-black/20 font-bold text-white/70 uppercase text-xs tracking-wider">
              {t.sidebarTitle}
           </div>
           <div className="flex flex-row overflow-x-auto lg:flex-col lg:overflow-visible p-2 gap-1">
              {STEPS.map((step, idx) => {
                  const isActive = activeStep === step.id;
                  const Icon = step.icon;
                  return (
                      <button
                        key={step.id}
                        onClick={() => setActiveStep(step.id)}
                        className={`
                            shrink-0 lg:w-full text-left px-4 py-3 rounded-xl flex items-center gap-3 transition-all
                            ${isActive ? "bg-white/10 text-white shadow-md border border-white/5" : "text-white/60 hover:bg-white/5 hover:text-white border border-transparent"}
                        `}
                      >
                         <div className={`p-1.5 rounded-lg ${isActive ? "bg-red-500/20 text-red-400" : "bg-white/5"}`}>
                            <Icon size={16} />
                         </div>
                         <span className="text-sm font-medium">{idx + 1}. {t.steps[step.id]}</span>
                      </button>
                  );
              })}
           </div>
        </div>

        {/* RIGHT CONTENT */}
        <div className="flex-1 bg-[#18181b] border border-white/10 rounded-2xl p-6 md:p-10 shadow-xl flex flex-col relative">
            
            <div className="flex-1 space-y-6">

                {/* 1. REQUIREMENTS */}
                {activeStep === "requirements" && (
                    <div className="space-y-6 animate-in fade-in slide-in-from-right-4 duration-300">
                        <h2 className="text-2xl font-bold border-b border-white/10 pb-4">{t.reqTitle}</h2>
                        <p className="text-white/70 leading-relaxed">
                            {t.reqText}
                        </p>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                            <a href="https://streamer.bot/" target="_blank" rel="noreferrer" className="group bg-black/30 hover:bg-black/50 border border-white/10 hover:border-violet-500/50 rounded-2xl p-6 transition-all">
                                <Bot size={40} className="text-violet-400 mb-4 group-hover:scale-110 transition-transform" />
                                <h3 className="text-xl font-bold mb-2">Streamer.bot</h3>
                                <p className="text-sm text-white/50">{t.reqSBDesc}</p>
                                <div className="mt-4 text-violet-400 text-sm font-bold flex items-center gap-1">Download <ChevronRight size={14}/></div>
                            </a>

                            <a href="https://github.com/pear-devs/pear-desktop/releases/tag/v3.11.0" target="_blank" rel="noreferrer" className="group bg-black/30 hover:bg-black/50 border border-white/10 hover:border-red-500/50 rounded-2xl p-6 transition-all">
                                <Music size={40} className="text-red-400 mb-4 group-hover:scale-110 transition-transform" />
                                <h3 className="text-xl font-bold mb-2">YTM Desktop App</h3>
                                <p className="text-sm text-white/50">{t.reqYTMDesc}</p>
                                <div className="mt-4 text-red-400 text-sm font-bold flex items-center gap-1">Download <ChevronRight size={14}/></div>
                            </a>
                        </div>
                    </div>
                )}

                {/* 2. SETUP YTM APP */}
                {activeStep === "ytm-setup" && (
                    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                        <h2 className="text-2xl font-bold border-b border-white/10 pb-4">{t.ytmTitle}</h2>
                        
                        <div className="space-y-4">
                            <div className="flex gap-4">
                                <div className="shrink-0 w-8 h-8 rounded-full bg-red-500/20 text-red-400 flex items-center justify-center font-bold">1</div>
                                <div>
                                    <h3 className="text-lg font-bold">{t.ytmLogin}</h3>
                                    <p className="text-white/60 text-sm mt-1">{t.ytmLoginText}</p>
                                </div>
                            </div>
                        </div>

                        <div className="space-y-4">
                            <div className="flex gap-4">
                                <div className="shrink-0 w-8 h-8 rounded-full bg-red-500/20 text-red-400 flex items-center justify-center font-bold">2</div>
                                <div>
                                    <h3 className="text-lg font-bold">{t.ytmApi}</h3>
                                    <p className="text-white/60 text-sm mt-1">{t.ytmApiText}</p>
                                    <p className="text-white/60 text-sm mt-1 font-semibold text-red-300">{t.ytmApiWarning}</p>
                                </div>
                            </div>
                            {/* PLACEHOLDER SCREENSHOT */}
                            <div className="ml-12 bg-black/40 border border-dashed border-white/20 rounded-xl overflow-hidden">
                                <img 
                                    src="/assets/tutorial/ytmsettings.png" 
                                    alt="Remote Settings" 
                                    className="w-full h-auto block" 
                                />
                            </div>
                        </div>
                    </div>
                )}

                {/* 3. SETUP STREAMER.BOT */}
                {activeStep === "sb-setup" && (
                    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                        <h2 className="text-2xl font-bold border-b border-white/10 pb-4">{t.sbTitle}</h2>

                        {/* Import Code Section */}
                        <div className="bg-black/30 border border-white/10 rounded-xl overflow-hidden">
                            <div className="flex items-center justify-between p-3 bg-white/5 border-b border-white/5">
                                <span className="text-xs font-bold text-white/50 uppercase">{t.sbImportLabel}</span>
                                <div className="flex items-center gap-2 px-2 py-1 rounded bg-violet-500/10 border border-violet-500/20 text-[10px]">
                                    <span className="text-violet-300 font-mono font-bold">
                                        {CODE_META.version}
                                    </span>
                                    <span className="w-1 h-1 rounded-full bg-white/20"></span>
                                    <span className="text-white/40">
                                        {t.sbUpdated} {CODE_META.date}
                                    </span>
                                </div>
                                <button 
                                    onClick={copyCode}
                                    className="flex items-center gap-2 px-3 py-1.5 bg-violet-600 hover:bg-violet-500 rounded-lg text-xs font-bold transition-colors"
                                >
                                    {copied ? <Check size={14} /> : <Copy size={14} />}
                                    {copied ? t.sbCopied : t.sbCopy}
                                </button>
                            </div>
                            <pre className="p-4 text-[10px] text-white/60 font-mono overflow-y-auto max-h-[150px] custom-scrollbar break-all whitespace-pre-wrap select-all">
                                {activeImportCode}
                            </pre>
                        </div>

                        <div className="space-y-2 text-sm text-white/70">
                            <p>{t.sbInstr1}</p>
                            <p>{t.sbInstr2}</p>
                            <p>{t.sbInstr3}</p>
                            <p>{t.sbInstr4}</p>
                        </div>

                        <div className="space-y-6 pt-4 border-t border-white/10">
                            <h3 className="text-xl font-bold text-violet-400">{t.sbActionTitle}</h3>
                            
                            {t.sbActions.map((action, i) => (
                                <div key={i} className="bg-white/5 border border-white/5 rounded-xl p-4">
                                    <div className="font-bold text-white mb-1">{action.title}</div>
                                    <div className="text-sm text-white/60">{action.desc}</div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}

                {/* 4. SETUP SPOTIFY */}
                {activeStep === "spotify" && (
                    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                        <h2 className="text-2xl font-bold border-b border-white/10 pb-4">{t.spTitle}</h2>
                        <p className="text-white/70">
                            {t.spText}
                        </p>

                        <a href="https://developer.spotify.com/dashboard" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 bg-[#1DB954] hover:bg-[#1ed760] text-black font-bold px-6 py-3 rounded-xl transition-colors">
                            {t.spBtn} <ChevronRight size={16} />
                        </a>

                        <div className="space-y-4 list-decimal list-inside text-white/80 text-sm leading-relaxed">
                             <div className="bg-black/30 p-4 rounded-xl border border-white/10">
                                {t.spStep1}<br/>
                                {t.spStep2}<br/>
                                {t.spStep3}<br/>
                                {t.spStep4}
                             </div>
                             
                             <div className="bg-violet-500/10 p-4 rounded-xl border border-violet-500/20 text-violet-200">
                                {t.spStep5}<br/>
                                {t.spStep6}<br/>
                                {t.spStep7}
                             </div>
                        </div>
                    </div>
                )}

                {/* 5. FEEDBACK */}
                {activeStep === "feedback" && (
                    <div className="space-y-8 animate-in fade-in slide-in-from-right-4 duration-300">
                        <h2 className="text-2xl font-bold border-b border-white/10 pb-4">{t.fbTitle}</h2>
                        
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                            
                            {/* Support Links */}
                            <div className="space-y-4">
                                <div className="p-5 bg-white/5 border border-white/10 rounded-2xl">
                                    <h3 className="font-bold mb-2 flex items-center gap-2"><Settings size={18} /> {t.fbHelpTitle}</h3>
                                    <p className="text-sm text-white/60 mb-4">{t.fbHelpText}</p>
                                    <a href="https://discord.gg/ecRJSx2R6x" target="_blank" rel="noreferrer" className="inline-block bg-[#5865F2] hover:bg-[#4752c4] px-4 py-2 rounded-lg font-bold text-sm transition-colors">
                                        {t.fbHelpBtn}
                                    </a>
                                </div>
                                <div className="p-5 bg-gradient-to-br from-blue-900/20 to-blue-600/10 border border-blue-500/20 rounded-2xl">
                                    <h3 className="font-bold mb-2 flex items-center gap-2"><Heart size={18} className="text-blue-400" /> {t.fbSupportTitle}</h3>
                                    <p className="text-sm text-white/60 mb-4">{t.fbSupportText}</p>
                                    <a href="https://paypal.me/vnmlol" target="_blank" rel="noreferrer" className="inline-block bg-[#0070BA] hover:bg-[#005ea6] px-4 py-2 rounded-lg font-bold text-sm transition-colors">
                                        PayPal
                                    </a>
                                </div>
                            </div>

                            {/* Rating Form */}
                            <div className="bg-black/30 border border-white/10 rounded-2xl p-6">
                                <h3 className="font-bold mb-4">{t.fbRateTitle}</h3>
                                {sent ? (
                                    <div className="h-full flex flex-col items-center justify-center text-center py-10">
                                        <div className="w-12 h-12 bg-green-500/20 text-green-400 rounded-full flex items-center justify-center mb-3">
                                            <Check size={24} />
                                        </div>
                                        <p className="text-lg font-bold">{t.fbThanks}</p>
                                    </div>
                                ) : (
                                    <div className="space-y-4">
                                        <div className="flex gap-2 justify-center py-2">
                                            {[1,2,3,4,5].map(star => (
                                                <button 
                                                    key={star} 
                                                    onClick={() => setRating(star)}
                                                    className={`transition-transform hover:scale-110 ${rating >= star ? "text-yellow-400" : "text-white/20"}`}
                                                >
                                                    <Star size={32} fill={rating >= star ? "currentColor" : "none"} />
                                                </button>
                                            ))}
                                        </div>
                                        <textarea 
                                            className="w-full h-32 bg-white/5 border border-white/10 rounded-xl p-3 text-sm focus:border-white/30 outline-none resize-none"
                                            placeholder={t.fbPlaceholder}
                                            value={feedbackText}
                                            onChange={e => setFeedbackText(e.target.value)}
                                        />
                                        <button 
                                            onClick={sendFeedback}
                                            disabled={!rating}
                                            className="w-full py-3 bg-white text-black font-bold rounded-xl hover:bg-gray-200 disabled:opacity-50 disabled:cursor-not-allowed"
                                        >
                                            {t.fbSend}
                                        </button>
                                    </div>
                                )}
                            </div>

                        </div>
                        {/* RELATED CONTENT */}
                        <div className="pt-6 border-t border-white/5">
                            <h3 className="text-sm font-bold uppercase text-white/50 mb-4 tracking-wider">{t.relTitle}</h3>
                            <Link to={`/tutorial/ytm-streamdeck?lang=${lang}`} className="group block bg-gradient-to-r from-blue-900/30 to-purple-900/30 border border-white/10 hover:border-blue-500/50 rounded-xl p-4 transition-all">
                                <div className="flex items-center justify-between">
                                    <div className="flex items-center gap-4">
                                        <div className="p-3 bg-black/40 rounded-lg text-blue-400 group-hover:scale-110 transition-transform">
                                            <Grid size={24} />
                                        </div>
                                        <div>
                                            <div className="font-bold text-lg text-white group-hover:text-blue-300 transition-colors">
                                                {t.relSdTitle}
                                            </div>
                                            <div className="text-sm text-white/60">
                                                {t.relSdText}
                                            </div>
                                        </div>
                                    </div>
                                    <div className="bg-white/10 p-2 rounded-full group-hover:bg-white/20 transition-colors">
                                        <ChevronRight size={20} />
                                    </div>
                                </div>
                            </Link>
                        </div>
                    </div>
                )}

            </div>

            {/* Bottom Navigation */}
            <div className="flex justify-between mt-8 pt-6 border-t border-white/5">
                <button 
                    onClick={goPrev} 
                    disabled={activeIndex === 0}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white/5 hover:bg-white/10 disabled:opacity-0 disabled:pointer-events-none transition-all"
                >
                    <ChevronLeft size={18} /> {t.navBack}
                </button>
                <button 
                    onClick={goNext}
                    disabled={activeIndex === STEPS.length - 1}
                    className="flex items-center gap-2 px-4 py-2 rounded-xl bg-white text-black font-bold hover:bg-gray-200 disabled:opacity-0 disabled:pointer-events-none transition-all shadow-lg"
                >
                    {t.navNext} <ChevronRight size={18} />
                </button>
            </div>
        </div>
      </div>
    </div>
  );
}